### PR TITLE
Make compatible with React 16.x.x and update old packages

### PR DESCRIPTION
**Pull request by Architektor**
Now snapguidist can be run in latest react environments, supporting react@16.x.x and related libraries.
Additionally i tweaked styles a bit (_to my taste_): removed gradients and made buttons neater
#27 can be closed after this will be merged

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Thank you very much @Architektor, but there are too many changes for a single PR.
From upgrading the deps, to changing the code style, to modifying the CSS.
It'd be great if you could split this into multiple ones.

**Comment by Architektor** [comment]
I'm really sorry for making a mess out of this PR, i will separate the 16.x.x support to a different PR and leave the style and css changes in my forked branch. By the way, is it fine that eslint was upgraded from 3.12.2 to 4.11.0 and some new rules were introduced or i should downgrade it back?

**Comment by poteirard** [comment]
I just installed snapguidist and it wasn't working because of this. I understand that having different PRs would be a better approach but considering the importance of this PR I would suggest to reconsider it in its current form. Thanks both of you for your work :)

**Comment by MicheleBertoli** [comment]
Hello @poteirard, thanks for your comment.
Instead of merging this PR which introduces unneeded breaking changes, would you be happy to submit a separate PR to upgrade just React?
Thank you very much!

**Comment by aldeed** [comment]
@MicheleBertoli see https://github.com/styleguidist/snapguidist/pull/29

**Comment by MicheleBertoli** [comment]
🎉

**Pull request closed without merging**
