### PR TITLE
Updated react-codemirror to react-codemirror2

### PR DESCRIPTION
**Pull request by iamtyce**
On @sapegin's advice this dependency should be updated to fix a bug with snapshot CSS highlighting.

**Context**:

* https://github.com/styleguidist/snapguidist/issues/23
* https://github.com/styleguidist/react-styleguidist/issues/611

### CODE REVIEW

**Comment by iamtyce** [comment]
Hmm.. looks like a snapshot failed in Travis.

**Comment by iamtyce** [comment]
Any ideas here, @MicheleBertoli?

**Comment by sapegin** [comment]
I think you just need to update snapshots. Do they work locally?

**Comment by iamtyce** [comment]
@MicheleBertoli Hopefully that did the trick!

**Comment by MicheleBertoli** [comment]
Thank you very much @iamtyce.
Can you please run `yarn add react-codemirror2@2.0.0` and commit the `yarn.lock` as well?

Also, I tried to run your branch and it seems all the style is gone (for both Styleguidist and Snapguidist code blocks):
screen shot 2017-09-27 at 21 59 41
Does it works for you?

**Comment by iamtyce** [comment]
@MicheleBertoli Updated the `yarn.lock` file but I am still seeing the missing styles locally 😞 so does that mean this fix doesn't solve the issue?

**Comment by MicheleBertoli** [comment]
Fixed in [v2.1.0](https://github.com/styleguidist/snapguidist/releases/tag/v2.1.0), thanks @iamtyce.

screen shot 2017-09-30 at 09 35 09

**Comment by iamtyce** [comment]
@MicheleBertoli Outstanding, thanks so much for the help! Please let me know if there's any UI things I can help Snapguidist on -- would love to contribute more 😄

**Comment by MicheleBertoli** [comment]
Any contribution to improve the UI is more than welcome.
One feature a lot of people are asking for, is the possibility to have a single "update" button (in the sidebar) to update all the failing snapshots in one go.
If you are interested we could open an issue and add more details.
Thank you very much.

**Pull request closed without merging**
